# Configure the .Site.Params variable for use in templates

# Google Analytics tracking ID.
googleAnalytics = "G-R12WP21VB3"

favicon = ""
description = ""
facebook = ""
twitter = "https://www.twitter.com/jerryryle"
instagram = ""
youtube = ""
github = "https://www.github.com/jerryryle"
gitlab = ""
linkedin = "https://www.linkedin.com/in/jerryryle"

# Choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"

body_classes = "avenir bg-near-white"
featured_image = "/images/banner.jpg"
recent_posts_number = 10
custom_css = []

