#!/usr/bin/env bash

HUGO_BUILD_FOLDER=${HUGO_BUILD_FOLDER:-"out"}

function leave()
{
	echo "$1"
	exit 1
}

echo "Using build folder: ${HUGO_BUILD_FOLDER?}"
if [ ! -d "${HUGO_BUILD_FOLDER}" ]; then
	echo "Creating build folder: ${HUGO_BUILD_FOLDER}"
	mkdir "${HUGO_BUILD_FOLDER}" || leave "unable to create build folder: ${HUGO_BUILD_FOLDER}"
else
	echo "Cleaning build folder: ${HUGO_BUILD_FOLDER}"
	cd "${HUGO_BUILD_FOLDER}" && rm -rf * && cd .. || leave "unable to clean build folder: ${HUGO_BUILD_FOLDER}"
fi

echo "Running Hugo"
export HUGO_ENV=production; hugo --destination "${HUGO_BUILD_FOLDER}" || leave "Hugo build failed"
