name: Build Site

# Controls when the action will run.
on:
  # Triggers the workflow on pull request for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables for all steps
    env:
      HUGO_BUILD_FOLDER: out

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0   # This gets all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Setup Tidy
        run: sudo apt-get install tidy

      - name: Hugo Build
        run: ./gen

      - name: Tidy HTML
        run: ./tidy

      - name: Archive Generated Site
        uses: actions/upload-artifact@v4
        with:
          name: generated-site
          path: ${{ env.HUGO_BUILD_FOLDER }}
