name: Build Site

on:
  workflow_call:
    inputs:
      hugo_version:
        description: The version of Hugo to use (e.g., 'latest')
        type: string
        required: false
        default: 'latest'
      site_artifact_name:
        description: "The name of the generated site artifact to upload"
        type: string
        required: false
        default: 'generated-site'

jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
      HUGO_BUILD_FOLDER: "out"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0   # This gets all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo_version }}
          extended: true

      - name: Setup tidy
        run: sudo apt-get install tidy

      - name: Build site
        run: |
          make all

      - name: Upload built site artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.site_artifact_name }}
          path: ${{ env.HUGO_BUILD_FOLDER }}
