name: Deploy Site

on:
  workflow_call:
    inputs:
      environment:
        description: "The Github environment to use"
        required: true
        type: string
      site_artifact_name:
        description: "The name of the generated site artifact to download and deploy"
        type: string
        required: false
        default: 'generated-site'

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      HUGO_BUILD_FOLDER: "out"
      S3_BUCKET_URI: ${{ vars.S3_BUCKET_URI }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download built site artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.site_artifact_name }}
          path: ${{ env.HUGO_BUILD_FOLDER }}

      - name: Configure AWS credentials from publish account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS
        run: |
          make deploy
